### ISSUE TITLE
Error while running test_2D.m

### ISSUE THREAD

**Issue by aatishanshuman** [KMountris/MFREE#1]
I am getting following error while running test_2D.m.

**Error using  - 
Matrix dimensions must agree.

Error in SupportNeighs (line 29)
    dist = sqrt(sum((nodes-points(i,:)).^2,2));

Error in test_2D (line 68)
[neighs] = SupportNeighs(eval, nodes, dc.*sd);**

**Comment by KMountris** [comment]
Hello aatish-5,

I couldn't reproduce the error. Are you sure that nodes is a [nx2] matrix and points a [px2] matrix? It should work for n=p and n!=p.

**Comment by aatish-5** [comment]
My bad. This error is encountered in an older version. Now it works.

**Comment by aatishanshuman** [comment]
Hi. Thanks for quick response.

My bad. I faced the problem with older version. It works fine.

**Comment by KMountris** [comment]
No worries! I hope you will find it useful :)
